version: "3"

services:
  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   ports:
  #     - "2181:2181"
  #   volumes:
  #     - "zookeeper_data:/bitnami"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  # kafka:
  #   image: bitnami/kafka:latest
  #   ports:
  #     - "9092:9092"
  #   volumes:
  #     - "kafka_data:/bitnami"
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  #   depends_on:
  #     - zookeeper

  redis:
    image: redis:6
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 1024M

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=alex.lu@decathlon.com
  #     - PGADMIN_DEFAULT_PASSWORD=test001
  #   restart: always
  #   ports:
  #     - 8081:80

  k8s-mig-db-old:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=test001
      - POSTGRES_USER=test001
      - POSTGRES_DB=messagehub
    volumes:
      - ./init/demo/source.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4096M
        reservations:
          cpus: "1"
          memory: 4096M

  k8s-mig-db-new:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=test001
      - POSTGRES_USER=test001
      - POSTGRES_DB=messagehub
    volumes:
      - ./init/demo/target.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "15432:5432"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4096M
        reservations:
          cpus: "1"
          memory: 4096M

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  default:
    external: true
    name: msghub-backend
